-- Create warehouse, database, schema
CREATE OR REPLACE WAREHOUSE WEATHER_WH WAREHOUSE_SIZE = XSMALL;
CREATE OR REPLACE DATABASE WEATHER_DB;
CREATE OR REPLACE SCHEMA RAW;

-- Set context
USE WAREHOUSE WEATHER_WH;
USE DATABASE WEATHER_DB;
USE SCHEMA RAW;

-- Raw table
CREATE OR REPLACE TABLE WEATHER_RAW (
    CITY STRING,
    DATE DATE,
    TIME STRING,
    TEMPERATURE FLOAT,
    HUMIDITY FLOAT,
    PRESSURE FLOAT,
    WIND_SPEED FLOAT,
    WEATHER STRING
);

DESC TABLE WEATHER_RAW;

-- Internal stage
CREATE OR REPLACE STAGE WEATHER_STAGE;

-- File format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

SELECT * FROM WEATHER_RAW;