CREATE OR REPLACE TABLE WEATHER_CLEAN AS
SELECT
    CITY,
    DATE,
    TIME,
    TEMPERATURE,
    HUMIDITY,
    PRESSURE,
    WIND_SPEED,
    UPPER(WEATHER) AS WEATHER,
    CASE
        WHEN TEMPERATURE > 35 THEN 'HOT'
        WHEN TEMPERATURE BETWEEN 25 AND 35 THEN 'WARM'
        WHEN TEMPERATURE BETWEEN 15 AND 24 THEN 'COOL'
        ELSE 'COLD'
    END AS TEMP_STATUS,
    -- Add a surrogate key for easier incremental loading (optional)
    ROW_NUMBER() OVER (ORDER BY DATE, TIME) AS ROW_ID   -- for uniqueness
FROM WEATHER_RAW;