-- Average temperature per day
CREATE OR REPLACE VIEW DAILY_TEMP_AVG AS
SELECT DATE, AVG(TEMPERATURE) AS AVG_TEMP
FROM WEATHER_CLEAN
GROUP BY DATE;

SHOW VIEWS LIKE 'DAILY_TEMP_AVG';

SELECT * FROM DAILY_TEMP_AVG;

-- Weather condition counts
CREATE OR REPLACE VIEW WEATHER_COUNTS AS
SELECT WEATHER, COUNT(*) AS COUNT
FROM WEATHER_CLEAN
GROUP BY WEATHER;

SHOW VIEWS LIKE 'WEATHER_COUNTS';

SELECT * FROM WEATHER_COUNTS;

-- Highest temperatures
CREATE OR REPLACE VIEW HIGHEST_TEMP AS
SELECT * FROM WEATHER_CLEAN
ORDER BY TEMPERATURE DESC LIMIT 10;

SHOW VIEWS LIKE 'HIGHEST_TEMP';

SELECT * FROM HIGHEST_TEMP;