-- Create a stream on the raw table
CREATE OR REPLACE STREAM WEATHER_STREAM ON TABLE WEATHER_RAW;

-- Create a task that runs every hour and inserts new records
CREATE OR REPLACE TASK WEATHER_TASK
    WAREHOUSE = WEATHER_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'   -- hourly
AS
    INSERT INTO WEATHER_CLEAN (CITY, DATE, TIME, TEMPERATURE, HUMIDITY, PRESSURE, WIND_SPEED, WEATHER, TEMP_STATUS)
    SELECT
        CITY, DATE, TIME, TEMPERATURE, HUMIDITY, PRESSURE, WIND_SPEED, WEATHER,
        CASE
            WHEN TEMPERATURE > 35 THEN 'HOT'
            WHEN TEMPERATURE BETWEEN 25 AND 35 THEN 'WARM'
            WHEN TEMPERATURE BETWEEN 15 AND 24 THEN 'COOL'
            ELSE 'COLD'
        END
    FROM WEATHER_STREAM
    WHERE METADATA$ACTION = 'INSERT';   -- only new rows

-- Resume the task (it starts suspended by default)
ALTER TASK WEATHER_TASK RESUME;